#!/usr/bin/env bash

echo "==delete bucket=="
# Check for backet name
if [ -z "$1" ]; then
    echo "There need to be a backet name"
    exit 1
fi

BUCKET_NAME=$1

aws s3api delete-bucket \
 --bucket $BUCKET_NAME \
